# This is a basic workflow to help you get started with Actions

name: CI-TF

# Controls when the workflow will run
on:
  #push:
    # only trigger on branches that have a tf/ prefix
  #  branches: '*'
  pull_request:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
  #  inputs:
  #    tf-options:
  #      type: choice
  #      description: Which tf file to run
  #      required: true
  #      options:
  #        - foo/gke.tf
  #        - bar/gke.tf
  #    environment:
  #        type: environment

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'http://cool.link.we.can.show.here.com'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Host Info
        run: lsb_release -a
        
      - uses: actions/checkout@v3
        with:
          # checkout full tree
          fetch-depth: 0
      - run: git remote -v
      - run: git branch -avv

      - run: git rev-list origin/main..origin/tf-test
      #- run: |
      #    for commit in $(git rev-list ${{ github.base_ref }}..${{ github.head_ref }}); do
      #        git checkout $commit
      #        echo "run test"
      #    done
        
  #TF:
  #      uses: ./.github/workflows/terraform.yml
  #      needs: [Setup]
  #      secrets:
  #        IDENTITYPROVIDER: ${{ secrets.IDENTITYPROVIDER }}
  #        SVC: ${{ secrets.SVC }}
  #        LOCATION: ${{ secrets.LOCATION }}
  #        CLUSTER: ${{ secrets.CLUSTER }}
  #        PROJECT: ${{ secrets.PROJECT }}
  #      with:
  #        fileName: "${{ inputs.tf-options }}"

